import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import { UserProdiver } from "@/features/components/providers/UserProvider";
import { Toast } from "@heroui/react";

const inter = Inter({
    variable: '--font-inter',
    subsets: ['latin'],
});

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const style = {
        background: "linear-gradient(90deg,rgba(255, 137, 6, 1) 0%, rgba(255, 255, 255, 1) 20%, rgba(255, 255, 255, 1) 100%)"
    }
    return (
        <html
            lang="en"
            className={`${geistSans.variable} ${geistMono.variable} ${inter.variable} h-full antialiased`}
        >
            <body className={`${inter.className} min-h-full flex flex-col`}>
                <Toast.Provider />
                <div className="flex flex-col">
                    <div className="flex flex-row gap-2 p-5 items-center" style={style}>
                        <img src="https://static.thenounproject.com/png/cash-flow-icon-3346770-512.png" alt="icon" className="w-20" />
                        <h1 className="text-5xl --font-inter">Cash<span className="text-orange-400 font-bold">Flow</span></h1>
                    </div>
                    <UserProdiver>
                        {children}
                    </UserProdiver>
                </div>
            </body>
        </html>
    );
}
